/* Generate the dashboard card YAML for a pack.
 *
 * The pack itself deliberately carries no entity ids, so somebody installing
 * it has to map their own. Doing that from memory means reading home.json to
 * find out which keys exist, which is exactly the tedium this file removes:
 * every bindable key is written out, grouped by room and labelled, ready to
 * have an entity typed next to it.
 *
 * Empty placeholders are `''` rather than omitted, so the list is visible in
 * the editor. An empty value reads as unbound, and an unbound fixture stays
 * dark on purpose instead of guessing at an entity.
 */

const INDENT = '  ';

/** Quote only where YAML needs it, so the output stays easy to read. */
function scalar(value) {
  const text = String(value);
  if (text === '') return "''";
  // A leading slash is fine unquoted, and pack paths all start with one.
  if (/^[A-Za-z0-9_/][A-Za-z0-9_.\-/]*$/.test(text)) return text;
  return `'${text.replace(/'/g, "''")}'`;
}

/** A comment can contain anything; just keep it on one line. */
function comment(text) {
  return String(text).replace(/\s*[\r\n]+\s*/g, ' ').trim();
}

function columnWidth(entries) {
  const longest = entries.reduce((max, entry) =>
    Math.max(max, `${INDENT}${INDENT}${entry.key}: ${entry.value}`.length), 0);
  // Cap it: one very long id should not push every comment off the screen.
  return Math.min(longest, 56);
}

function describeFixture(fixture) {
  const parts = [];
  if (fixture.kind && fixture.kind !== 'light') parts.push(fixture.kind);
  const bulbs = fixture.emitters?.length ?? 0;
  if (bulbs > 1) parts.push(`${bulbs} bulbs`);
  const type = fixture.emitters?.[0]?.type;
  if (type && type !== 'point') parts.push(type);
  const name = fixture.name || fixture.id;
  return parts.length ? `${name} · ${parts.join(', ')}` : name;
}

/**
 * @param {object} manifest the generated home.json
 * @param {object} options
 * @returns {string} YAML ready to paste into a manual dashboard card
 */
export function buildCardYaml(manifest, { version = '0.1.0', packPath = null } = {}) {
  const pack = manifest.pack || {};
  const id = pack.id || 'home';
  const home = packPath || `/local/domoview/homes/${id}`;
  const rooms = manifest.rooms || [];
  const roomName = new Map(rooms.map(room => [room.id, room.name || room.id]));
  const lines = [];

  lines.push(
    `# DomoView card for "${comment(pack.name || id)}"`,
    `# Generated by DomoView Studio ${version}`,
    '#',
    '# 1. Copy the pack folder next to this file into your Home Assistant config:',
    `#      /config/www/domoview/homes/${id}/`,
    '#    so that /config/www/domoview/homes/' + id + '/home.json exists.',
    '#',
    '# 2. Paste everything below into a dashboard card:',
    '#      Edit dashboard → + Add card → Manual',
    '#',
    '# 3. Replace each \'\' with one of your entities. You can also do this in the',
    '#    card\'s visual editor, which lists the same keys with entity pickers.',
    '#',
    '# Keep this file OUT of /config/www. Anything under www is served without',
    '# authentication, and once you fill it in this lists your entity ids.',
    '',
    `type: custom:domoview-card`,
    `home: ${scalar(home)}`,
  );

  const cameras = manifest.cameras || [];
  if (cameras.length > 1) {
    const preferred = cameras.find(camera => camera.default) || cameras[0];
    lines.push(`camera: ${scalar(preferred.id)}   # ${comment(cameras.map(c => c.id).join(', '))}`);
  }
  if ((manifest.variants || []).length) {
    lines.push(`# variant: ${manifest.variants[0].id}   # ${comment(manifest.variants.map(v => v.name).join(', '))}`);
  }
  lines.push('# renderer: auto      # auto | live3d | baked');
  lines.push('# quality: medium     # low | medium | high');

  // -- fixtures ------------------------------------------------------------
  const bindable = (manifest.fixtures || []).filter(fixture => fixture.kind !== 'marker');
  if (!bindable.length) {
    lines.push('', 'entities: {}   # this pack defines no bindable fixtures');
  } else {
    lines.push('', 'entities:');
    const byRoom = new Map();
    for (const fixture of bindable) {
      const key = fixture.room || '';
      if (!byRoom.has(key)) byRoom.set(key, []);
      byRoom.get(key).push(fixture);
    }
    let first = true;
    for (const [room, fixtures] of byRoom) {
      if (!first) lines.push('');
      first = false;
      lines.push(`${INDENT}# ${comment(roomName.get(room) || 'Unassigned')}`);
      const entries = fixtures.map(fixture => ({
        key: fixture.id, value: "''", note: describeFixture(fixture),
      }));
      // One indent level less than `aligned` assumes, since these sit directly
      // under `entities:`.
      const width = columnWidth(entries) - INDENT.length;
      for (const entry of entries) {
        const left = `${INDENT}${entry.key}: ${entry.value}`;
        lines.push(entry.note ? `${left.padEnd(width)}  # ${comment(entry.note)}` : left);
      }
    }
  }

  // -- covers --------------------------------------------------------------
  const covered = (manifest.openings || []).filter(opening => opening.cover);
  lines.push('', '# Blinds and shutters. Needs a cover.* entity that reports current_position.');
  if (!covered.length) {
    lines.push('covers: {}   # no window in this pack is marked as having a blind');
  } else {
    lines.push('covers:');
    const entries = covered.map(opening => ({
      key: opening.id, value: "''", note: opening.name || opening.id,
    }));
    const width = columnWidth(entries) - INDENT.length;
    for (const entry of entries) {
      lines.push(`${INDENT}${entry.key}: ${entry.value}`.padEnd(width) + `  # ${comment(entry.note)}`);
    }
  }

  // -- window contacts ----------------------------------------------------
  const windows = (manifest.openings || []).filter(opening => opening.type !== 'door');
  lines.push('', '# Optional. A window reported open gets a small badge above it.');
  if (!windows.length) {
    lines.push('window_sensors: {}');
  } else {
    lines.push('window_sensors:');
    const entries = windows.map(opening => ({
      key: opening.id, value: "''", note: opening.name || opening.id,
    }));
    const width = columnWidth(entries) - INDENT.length;
    for (const entry of entries) {
      lines.push(`${INDENT}${entry.key}: ${entry.value}`.padEnd(width) + `  # ${comment(entry.note)}`);
    }
  }

  // -- room climate --------------------------------------------------------
  lines.push('', '# Optional. Only rooms with a reading get a temperature/humidity chip.');
  if (!rooms.length) {
    lines.push('rooms: {}');
  } else {
    lines.push('rooms:');
    for (const room of rooms) {
      lines.push(`${INDENT}${room.id}:   # ${comment(room.name || room.id)}`);
      lines.push(`${INDENT}${INDENT}temperature: ''`);
      lines.push(`${INDENT}${INDENT}humidity: ''`);
    }
  }

  // -- scene inputs --------------------------------------------------------
  lines.push(
    '',
    '# Sun and weather. All optional: without them DomoView uses sun.sun, the',
    '# first available weather.* entity, and your Home Assistant location.',
    '# An irradiance sensor is the single biggest improvement to how light reads,',
    '# because a thin overcast and a bright haze report the same condition.',
    'sun_entity: sun.sun',
    '# weather_entity: weather.home',
    '# cloud_entity: sensor.cloud_coverage',
    '# irradiance_entity: sensor.solar_radiation',
    '# illuminance_entity: sensor.outdoor_illuminance',
    '# rain_entity: binary_sensor.rain',
    '# snow_entity: binary_sensor.snow',
    '# precipitation_rate_entity: sensor.rain_rate',
    '# wind_speed_entity: sensor.wind_speed',
    '# snow_depth_entity: sensor.snow_depth',
    '# moon_entity: sensor.moon_phase',
    '',
  );

  return lines.join('\n');
}

/** Counts shown in the export panel, so you know what you are about to map. */
export function cardYamlSummary(manifest) {
  return {
    fixtures: (manifest.fixtures || []).filter(fixture => fixture.kind !== 'marker').length,
    covers: (manifest.openings || []).filter(opening => opening.cover).length,
    windows: (manifest.openings || []).filter(opening => opening.type !== 'door').length,
    rooms: (manifest.rooms || []).length,
  };
}
